// Auto-generated by build_bank.py. SGB built-in SFX bank index table.
// Bank file: sgb_sfx_bank.bin. Record = 16 bytes: {u32 offset,u32 length,u32 loop_offset,u32 sample_count}.
// loop_offset = byte offset of loop-start block within the stream, 0xFFFFFFFF = one-shot.
`define SGB_SFX_COUNT 7
`define SGB_SFX_TABLE_OFF 59200
`define SGB_SFX_BANK_BYTES 59312
// record 0: A0C_ExplosionSmall.wav offset=0 bytes=20421 loop=0xffffffff samples=36291
// record 1: A1F_SwordSwing.wav offset=20432 bytes=6381 loop=0xffffffff samples=11329
// record 2: A26_PictureFloats.wav offset=26816 bytes=7641 loop=0xffffffff samples=13569
// record 3: A30_SmallLaser.wav offset=34464 bytes=4941 loop=0xffffffff samples=8769
// record 4: B01_ApplauseSmall.wav offset=39408 bytes=5175 loop=0x345 samples=9199
// record 5: B04_Wind.wav offset=44592 bytes=10530 loop=0x10ce samples=18718
// record 6: B07_StormThunder.wav offset=55136 bytes=4059 loop=0x3f9 samples=7214
