// Auto-generated by build_bank.py. SGB built-in SFX bank index table.
// Bank file: sgb_sfx_bank.bin. Record = 16 bytes: {u32 offset,u32 length,u32 loop_offset,u32 sample_count}.
// loop_offset = byte offset of loop-start block within the stream, 0xFFFFFFFF = one-shot.
`define SGB_SFX_COUNT 8
`define SGB_SFX_TABLE_OFF 87680
`define SGB_SFX_BANK_BYTES 87808
// record 0: A1F_SwordSwing.wav offset=0 bytes=6381 loop=0xffffffff samples=11329
// record 1: A26_PictureFloats.wav offset=6384 bytes=7641 loop=0xffffffff samples=13569
// record 2: A30_SmallLaser.wav offset=14032 bytes=4941 loop=0xffffffff samples=8769
// record 3: B01_ApplauseSmall.wav offset=18976 bytes=5175 loop=0x345 samples=9199
// record 4: B04_Wind.wav offset=24160 bytes=10530 loop=0x10ce samples=18718
// record 5: B07_StormThunder.wav offset=34704 bytes=4059 loop=0x3f9 samples=7214
// record 6: B08_LightningB.wav offset=38768 bytes=23796 loop=0x57d2 samples=42300
// record 7: B0B_Wave.wav offset=62576 bytes=25101 loop=0xffffffff samples=44610
