// Auto-generated by build_bank_pcm.py. UNCOMPRESSED 16-bit mono PCM bank.
// Bank file: sgb_sfx_bank.bin. Record = 16 bytes: {u32 offset,u32 length,u32 loop_offset,u32 sample_count}.
// loop_offset = byte offset of loop point, 0xFFFFFFFF = one-shot.
`define SGB_SFX_COUNT 8
`define SGB_SFX_TABLE_OFF 311488
`define SGB_SFX_BANK_BYTES 311616
// record 0: A1F_SwordSwing.wav offset=0 bytes=22660 loop=0xffffffff samples=11330
// record 1: A26_PictureFloats.wav offset=22672 bytes=27140 loop=0xffffffff samples=13570
// record 2: A30_SmallLaser.wav offset=49824 bytes=17540 loop=0xffffffff samples=8770
// record 3: B01_ApplauseSmall.wav offset=67376 bytes=18400 loop=0xba0 samples=9200
// record 4: B04_Wind.wav offset=85776 bytes=37436 loop=0x3bc0 samples=18718
// record 5: B07_StormThunder.wav offset=123216 bytes=14428 loop=0xe20 samples=7214
// record 6: B08_LightningB.wav offset=137648 bytes=84600 loop=0x13840 samples=42300
// record 7: B0B_Wave.wav offset=222256 bytes=89220 loop=0xffffffff samples=44610
