#!/usr/bin/env python3
# Build the SGB built-in SFX bank as UNCOMPRESSED 16-bit mono PCM.
#
# Unlike build_bank.py (BRR-compressed), this packs raw 16 kHz mono 16-bit
# little-endian PCM. Quality is the rendered WAV itself (no compression
# artifacts); the cost is size (~32 KB/s vs BRR's ~3.5 KB/s).
#
# Bank layout (sgb_sfx_bank.bin):
#   [ PCM streams, each 16-byte aligned ][ index table ]
# Index table record (16 bytes, little-endian), one per effect:
#   u32 offset        byte offset of the PCM stream within the bank
#   u32 length        PCM byte count (even; 2 bytes/sample)
#   u32 loop_offset   byte offset (within the stream) of the loop point,
#                     0xFFFFFFFF = one-shot
#   u32 sample_count  decoded sample count
#
# Usage:
#   python3 build_bank_pcm.py [--rate 16000] [--wav ./wav] [--out ./bank_pcm]
#                             [--only A1F,A26,...]
import wave, struct, json, os, argparse

# Reuse the mono downmix/resample + loop detection from the BRR builder.
from build_bank import load_wav_mono, detect_loop

ALIGN = 16

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--rate', type=int, default=16000)
    base = os.path.dirname(os.path.abspath(__file__))
    ap.add_argument('--wav', default=os.path.join(base, 'wav'))
    ap.add_argument('--out', default=os.path.join(base, 'bank_pcm'))
    ap.add_argument('--only', default='', help='comma-separated stems, e.g. A1F,B04')
    a = ap.parse_args()
    os.makedirs(a.out, exist_ok=True)
    only = set(s.strip().lower() for s in a.only.split(',') if s.strip())

    bank = bytearray()
    table = []
    man = {}
    for fn in sorted(os.listdir(a.wav)):
        if not fn.endswith('.wav') or fn[0] not in 'AB':
            continue
        stem = fn[:3].lower()
        if only and stem not in only:
            continue
        mono = load_wav_mono(os.path.join(a.wav, fn), a.rate)
        if max(abs(x) for x in mono) < 64:
            print(f"skip silent {fn}")
            continue
        loop_start = None
        keep = len(mono)
        if fn[0] == 'B':
            det = detect_loop(mono, a.rate)
            if det:
                loop_start, loop_len, keep = det
        mono = mono[:keep]
        # pad stream to an even sample count so it ends word-aligned
        if len(mono) % 2:
            mono.append(0)
        pcm = struct.pack('<%dh' % len(mono), *mono)
        pad = (ALIGN - (len(bank) % ALIGN)) % ALIGN
        bank += b'\x00' * pad
        off = len(bank)
        bank += pcm
        loop_off = (loop_start * 2) if loop_start is not None else 0xFFFFFFFF
        table.append((fn, off, len(pcm), loop_off, len(mono)))
        man[fn] = {'record': len(table)-1, 'offset': off, 'bytes': len(pcm),
                   'loop_offset': loop_off if loop_off != 0xFFFFFFFF else None,
                   'samples': len(mono), 'rate': a.rate}
        ls = f"loop@{loop_off}" if loop_off != 0xFFFFFFFF else "one-shot"
        print(f"{fn}: {len(mono)} smp@{a.rate} -> {len(pcm)}B {ls}")

    pad = (ALIGN - (len(bank) % ALIGN)) % ALIGN
    bank += b'\x00' * pad
    tbl_off = len(bank)
    for (fn, off, ln, loop_off, nsmp) in table:
        bank += struct.pack('<IIII', off, ln, loop_off, nsmp)

    open(os.path.join(a.out, 'sgb_sfx_bank.bin'), 'wb').write(bytes(bank))
    hdr = (f"// Auto-generated by build_bank_pcm.py. UNCOMPRESSED 16-bit mono PCM bank.\n"
           f"// Bank file: sgb_sfx_bank.bin. Record = 16 bytes: "
           f"{{u32 offset,u32 length,u32 loop_offset,u32 sample_count}}.\n"
           f"// loop_offset = byte offset of loop point, 0xFFFFFFFF = one-shot.\n"
           f"`define SGB_SFX_COUNT {len(table)}\n"
           f"`define SGB_SFX_TABLE_OFF {tbl_off}\n"
           f"`define SGB_SFX_BANK_BYTES {len(bank)}\n")
    for i, (fn, off, ln, loop_off, nsmp) in enumerate(table):
        hdr += f"// record {i}: {fn} offset={off} bytes={ln} loop={loop_off:#x} samples={nsmp}\n"
    open(os.path.join(a.out, 'sgb_sfx_bank.vh'), 'w').write(hdr)
    json.dump(man, open(os.path.join(a.out, 'sgb_sfx_bank.json'), 'w'), indent=1)

    # sim_bank.hex for the testbench (16-bit words, little-endian)
    with open(os.path.join(a.out, 'sim_bank.hex'), 'w') as f:
        for i in range(0, len(bank), 2):
            f.write("%04x\n" % (bank[i] | (bank[i+1] << 8)))

    tot = sum(t[2] for t in table)
    print(f"\nTOTAL {len(table)} effects | bank {len(bank)} B ({len(bank)/1024:.0f} KB) "
          f"| PCM {tot} B ({tot/1024:.0f} KB) | table @{tbl_off}")

if __name__ == '__main__':
    main()
