// tb_sgb_sfx_play.v -- verify the BRR HLE player (sgb_sfx_play) against the
// real ROM-native bank (build/sim_bank.hex) and the reference decodes
// (build/ref_XXX.hex, generated by extract_apu.py with the same decode math).
//
// The PSRAM arbiter is modeled (request/latency/done with random bubbles)
// over a word memory loaded from sim_bank.hex. Every record's `tick` word
// AND every segment entry's next-tick word is patched to 3 after load: ticks
// only pace the sample emit rate, they cannot change sample VALUES, so the
// comparison stays bit-exact while the sim runs ~1000x faster than real-time
// rates (and the envelope sequencer still steps its real boundaries).
//
// Per effect (record v5, see sgb_sfx_play.v header):
//   flags bit1 (loop forever): capture first pass + one loop pass (= the ref
//     stream length), then hStop; verify stop halts output promptly.
//   flags bit0 only (count-limited one-shot): run to natural end; expect
//     count*16 samples == ref length.
//   flags == 0 (plain one-shot): run to natural end; expect blocks*16.
// Every capture is compared SAMPLE-EXACTLY against ref_XXX.hex. Any byte
// alignment, pad-skip, loop-jump, predictor-history or decode bug breaks
// this. Envelope timing itself is covered by tb_sgb_sfx_env.v at real ticks.
`timescale 1ns/1ps
module tb_sgb_sfx_dbg;

    localparam [22:0] BANK_BASE = 23'h100000;
    localparam BANK_WORDS = 23788;        // 47576 bytes / 2 (bank v5)
    localparam SEG_WBASE  = 21664;        // segment region word base (0xA940/2)
    localparam MAXS       = 320000;       // biggest effect = A2D 19553*16 = 312848

    reg xClk = 0, hClk = 0;
    always #6.667  xClk = ~xClk;          // 75 MHz
    always #29.801 hClk = ~hClk;          // 16.777 MHz

    reg xReset = 1, hReset = 1;
    initial begin xReset = 1; hReset = 1; #400; xReset = 0; hReset = 0; end

    // ---- DUT interface ----
    wire        xRamReq_w;
    wire [22:0] xRamAddr_w;
    wire [10:0] xRamBurstLen_w;
    reg         xRamReady = 0;
    reg         xRamDone = 0, xRamDoutValid = 0;
    reg  [15:0] xRamDout = 0;
    reg         hStart = 0, hStop = 0;
    reg  [6:0]  hEffectIndex = 0;
    wire        hPcmValid;
    wire signed [15:0] hPcm;
    wire        hPlaying;

    sgb_sfx_play #(.BANK_BASE(BANK_BASE)) dut (
        .xClk(xClk), .xReset(xReset), .xRamReady(xRamReady),
        .xRamReq(xRamReq_w), .xRamRnW(), .xRamAddr(xRamAddr_w),
        .xRamDin(), .xRamBurstLen(xRamBurstLen_w),
        .xRamDone(xRamDone), .xRamDoutValid(xRamDoutValid), .xRamDout(xRamDout),
        .hClk(hClk), .hReset(hReset),
        .hStart(hStart), .hStop(hStop), .hEffectIndex(hEffectIndex),
        .hPcmValid(hPcmValid), .hPcm(hPcm), .hPlaying(hPlaying)
    );

    // ---- PSRAM contents: the ROM-native bank (header + table + BRR region) ----
    reg [15:0] psram [0:BANK_WORDS-1];
    integer i;
    integer w;
    initial begin
        $readmemh("sgb_sfx/build/sim_bank.hex", psram);
        // sim-speed patch: tick (record word 2 in v5) -> 3 for every effect,
        // and every segment entry's next-tick word -> 3. This only changes
        // the emit pacing; sample values are untouched, so the bit-exact
        // comparison against ref_XXX.hex remains valid (the envelope
        // sequencer still steps its real block boundaries).
        for (i = 0; i < 73; i = i + 1) psram[128 + i*8 + 2] = 16'd3;
        for (w = SEG_WBASE + 1; w < BANK_WORDS; w = w + 2) psram[w] = 16'd3;
    end

    function [15:0] rd_word;
        input [22:0] a;
        integer w;
        begin
            w = (a - BANK_BASE) >> 1;
            rd_word = (w >= 0 && w < BANK_WORDS) ? psram[w] : 16'h0000;
        end
    endfunction

    // record word w (0..7) of effect idx straight from the bank table
    function [15:0] rec_word;
        input [6:0] idx;
        input [2:0] w;
        begin
            rec_word = psram[128 + idx*8 + w];
        end
    endfunction

    // ---- arbiter / PSRAM read model ----
    // grant after a random latency, then stream words with random bubbles.
    localparam ARB_IDLE=0, ARB_LAT=1, ARB_RUN=2;
    reg [1:0]  arb_st = ARB_IDLE;
    reg [5:0]  arb_lat = 0;
    reg [22:0] rd_addr = 0;
    reg [10:0] rd_rem = 0;
    reg [2:0]  bubble = 0;

    always @(posedge xClk) begin
        if (xReset) begin
            arb_st <= ARB_IDLE; xRamDone <= 0; xRamDoutValid <= 0; rd_rem <= 0;
        end else begin
            xRamDoutValid <= 0;
            xRamDone      <= 0;
            case (arb_st)
            ARB_IDLE: begin
                if (xRamReq_w && xRamReady) begin
                    arb_st  <= ARB_LAT;
                    arb_lat <= $urandom_range(20, 2);   // arbiter/PSRAM latency
                    rd_addr <= xRamAddr_w;
                    rd_rem  <= xRamBurstLen_w;
                end
            end
            ARB_LAT: begin
                if (arb_lat == 0) arb_st <= ARB_RUN;
                else arb_lat <= arb_lat - 1;
            end
            ARB_RUN: begin
                if (bubble != 0) begin
                    bubble <= bubble - 1;
                end else if (rd_rem != 0) begin
                    xRamDout      <= rd_word(rd_addr);
                    xRamDoutValid <= 1;
                    rd_addr       <= rd_addr + 2;
                    rd_rem        <= rd_rem - 2;
                    if ($urandom_range(7,0) == 0) bubble <= $urandom_range(4,1);
                    if (rd_rem == 2) begin
                        xRamDone <= 1;
                        arb_st   <= ARB_IDLE;
                    end
                end
            end
            endcase
        end
    end

    // ---- capture + reference buffers ----
    reg signed [15:0] pcm_buf [0:MAXS-1];
    reg        [15:0] ref_buf [0:MAXS-1];
    integer ncap = 0;
    reg cap_en = 0;
    always @(posedge hClk) begin
        if (cap_en && hPcmValid && ncap < MAXS) begin
            pcm_buf[ncap] <= hPcm;
            ncap <= ncap + 1;
        end
    end

    // ---- record fields of the effect under test ----
    reg [31:0] r_brr, r_loop;
    reg [15:0] r_tick, r_blocks, r_flags, r_count;
    integer    exp_samples;      // expected capture/ref length in samples

    task load_rec;
        input [6:0] idx;
        begin
            // bank v5: all fields are u16; brr/loop are byte offsets into the
            // BRR region (record words 0/1), tick=word2, blocks=3, flags=4,
            // count=5, seg_off=6, seg_cnt=7
            r_brr    = {16'd0, rec_word(idx,0)};
            r_loop   = {16'd0, rec_word(idx,1)};
            r_tick   = rec_word(idx,2);
            r_blocks = rec_word(idx,3);
            r_flags  = rec_word(idx,4);
            r_count  = rec_word(idx,5);
            // ref stream length (see extract_apu.py::decode_stream):
            //   loop-forever: first pass + one loop pass
            //   count one-shot: count blocks; plain one-shot: blocks blocks
            if (r_flags[1])
                exp_samples = (r_blocks + (r_blocks*16'd9 - (r_loop - r_brr))/9) * 16;
            else if (r_flags[0])
                exp_samples = r_count * 16;
            else
                exp_samples = r_blocks * 16;
        end
    endtask

    // build "sgb_sfx/build/ref_XXX.hex" for idx and load it into ref_buf
    reg [8*25-1:0] path;
    function [7:0] hexdig;
        input [3:0] v;
        begin
            hexdig = (v < 4'd10) ? (8'h30 + {4'd0, v}) : (8'h37 + {4'd0, v});
        end
    endfunction
    task load_ref;
        input [6:0] idx;
        integer num;
        begin
            num  = (idx < 7'd48) ? (idx + 1) : (idx - 47);
            path = {"sgb_sfx/build/ref_",
                    (idx < 7'd48) ? 8'h41 : 8'h42,     // 'A' / 'B'
                    hexdig(num[7:4]), hexdig(num[3:0]), ".hex"};
            $readmemh(path, ref_buf);
        end
    endtask

    integer fails = 0;
    integer ndiff, k;

    task compare_cap;
        input integer off;       // offset into pcm_buf
        input integer n;         // number of samples to compare
        integer first_bad;
        begin
            ndiff = 0; first_bad = -1;
            for (k = 0; k < n; k = k + 1) begin
                if (pcm_buf[off + k] !== ref_buf[k]) begin
                    ndiff = ndiff + 1;
                    if (first_bad < 0) first_bad = k;
                    if (ndiff <= 8)
                        $display("    diff[%0d] rtl=%04x ref=%04x",
                                 k, pcm_buf[off + k], ref_buf[k]);
                end
            end
            if (ndiff == 0)
                $display("  EXACT    %0d samples", n);
            else begin
                fails = fails + 1;
                $display("  MISMATCH %0d diffs of %0d (first @%0d)", ndiff, n, first_bad);
            end
        end
    endtask

    task start_fx;
        input [6:0] idx;
        begin
            @(posedge hClk); hEffectIndex <= idx; hStart <= 1;
            @(posedge hClk); hStart <= 0;
        end
    endtask

    task stop_fx;
        begin
            @(posedge hClk); hStop <= 1;
            @(posedge hClk); hStop <= 0;
        end
    endtask

    // play a one-shot effect to its natural end and compare bit-exact
    task play_oneshot_check;
        input [6:0] idx;
        input integer timeout_ms;
        integer t, tmax;
        begin
            load_rec(idx); load_ref(idx);
            ncap = 0; cap_en = 1;
            start_fx(idx);
            t = 0; tmax = timeout_ms * 75000;      // xClk cycles
            while (!hPlaying && t < tmax) begin @(posedge xClk); t=t+1; end
            while ( hPlaying && t < tmax) begin @(posedge xClk); t=t+1; end
            repeat (200) @(posedge hClk);          // drain
            cap_en = 0;
            if (t >= tmax) begin
                fails = fails + 1;
                $display("FAIL fx%0d: timed out (playing=%b ncap=%0d/%0d)",
                         idx, hPlaying, ncap, exp_samples);
            end else if (ncap !== exp_samples) begin
                fails = fails + 1;
                $display("FAIL fx%0d: captured %0d samples, expected %0d",
                         idx, ncap, exp_samples);
            end else compare_cap(0, exp_samples);
        end
    endtask

    // play a loop-forever effect, capture first pass + one loop pass, stop it,
    // and compare bit-exact; also verify the stop actually halts the output
    integer nstop;
    task play_loop_check;
        input [6:0] idx;
        input integer timeout_ms;
        integer t, tmax;
        begin
            load_rec(idx); load_ref(idx);
            ncap = 0; cap_en = 1;
            start_fx(idx);
            t = 0; tmax = timeout_ms * 75000;
            while (ncap < exp_samples && t < tmax) begin @(posedge xClk); t=t+1; end
            stop_fx;
            repeat (8) @(posedge hClk);
            if (hPlaying) begin
                fails = fails + 1;
                $display("FAIL fx%0d: still playing 8 cycles after stop", idx);
            end
            nstop = ncap;
            repeat (200) @(posedge hClk);
            cap_en = 0;
            if (ncap !== nstop) begin
                fails = fails + 1;
                $display("FAIL fx%0d: %0d samples emitted AFTER stop", idx, ncap-nstop);
            end
            if (t >= tmax) begin
                fails = fails + 1;
                $display("FAIL fx%0d: capture timed out (%0d/%0d)", idx, ncap, exp_samples);
            end else if (ncap < exp_samples) begin
                fails = fails + 1;
                $display("FAIL fx%0d: capture short %0d < %0d", idx, ncap, exp_samples);
            end else compare_cap(0, exp_samples);
        end
    endtask

    // interrupt/retrigger: play the loop-forever B01, interrupt it mid-stream
    // with the one-shot A09; the TAIL of the capture (A09's full output) must
    // be bit-exact against ref_A09. A few old-stream samples leak between the
    // retrigger and the FIFO flush -- they land ahead of A09's region.
    integer mark;
    task play_interrupt_check;
        input [6:0] idx_a;     // first (looping) effect
        input [6:0] idx_b;     // interrupting one-shot
        input integer hold;    // samples of A before the interrupt
        input integer timeout_ms;
        integer t, tmax;
        begin
            ncap = 0; cap_en = 1;
            start_fx(idx_a);
            t = 0; tmax = timeout_ms * 75000;
            while (ncap < hold && t < tmax) begin @(posedge xClk); t=t+1; end
            load_rec(idx_b); load_ref(idx_b);
            start_fx(idx_b); mark = ncap;
            while (!hPlaying && t < tmax) begin @(posedge xClk); t=t+1; end
            // hPlaying stays high (old stream), then the one-shot ends
            while ( hPlaying && t < tmax) begin @(posedge xClk); t=t+1; end
            repeat (200) @(posedge hClk);
            cap_en = 0;
            stop_fx;                                 // belt-and-braces
            if (t >= tmax) begin
                fails = fails + 1;
                $display("FAIL int %0d->%0d: timed out", idx_a, idx_b);
            end else if (ncap - mark < exp_samples) begin
                fails = fails + 1;
                $display("FAIL int %0d->%0d: only %0d of %0d new samples",
                         idx_a, idx_b, ncap - mark, exp_samples);
            end else compare_cap(ncap - exp_samples, exp_samples);
        end
    endtask

    // heartbeat: catches hangs; prints which effect is under test
    reg [6:0] cur_idx = 0;
    integer hb = 0;
    always @(posedge xClk) begin
        hb = hb + 1;
        if (hb % 5000000 == 0)
            $display("hb: xClk=%0d simtime=%t fx=%0d ncap=%0d", hb, $time, cur_idx, ncap);
    end

    // stall monitor: dump the DUT when nothing moves for 200k xClk mid-test
    integer last_ncap = 0, prog_cycle = 0, dumped = 0;
    reg [3:0] last_st = 0; reg [9:0] last_wbin = 0; reg last_hp = 0;
    always @(posedge xClk) begin
        if (ncap !== last_ncap || dut.st !== last_st ||
            dut.wbin !== last_wbin || hPlaying !== last_hp) begin
            prog_cycle = hb; dumped = 0;
        end
        last_ncap = ncap; last_st = dut.st; last_wbin = dut.wbin; last_hp = hPlaying;
        if (cap_en && !dumped && hb - prog_cycle > 200000) begin
            dumped = 1;
            $display("STALL at hb=%0d fx=%0d ncap=%0d", hb, cur_idx, ncap);
            $display("  st=%0d req=%b cmdp=%b pplay=%b sdone=%b ack=%0d acklast=%0d cmdseq=%0d",
                     dut.st, dut.req_out, dut.cmd_pend, dut.pend_play,
                     dut.seg_done, dut.ack_seq, dut.ack_last, dut.cmd_seq);
            $display("  run=%b flush=%b ninit=%b play=%b wbin=%0d rbin=%0d wbin_h=%0d rbin_x=%0d",
                     dut.run_state, dut.flush_active, dut.need_init, hPlaying,
                     dut.wbin, dut.rbin, dut.wbin_h, dut.rbin_x);
            $display("  segst=%0d segon=%b segblk=%0d segleft=%0d hsegcnt=%0d htick=%0d tickcnt=%0d",
                     dut.seg_st, dut.seg_on, dut.seg_blk, dut.seg_left,
                     dut.h_seg_cnt, dut.h_tick, dut.tick_cnt);
            $display("  dstate=%0d nib=%0d haveb=%b sbv=%b wbufv=%b rdp=%b segrem=%0d skip=%0d blkrem=%0d words_avail=%b",
                     dut.dstate, dut.nib_i, dut.have_dbyte, dut.sb_v,
                     dut.wbuf_v, dut.rd_pend, dut.seg_rem, dut.skip_cnt,
                     dut.blk_rem, dut.words_avail);
        end
    end

    initial begin
        $display("TB START (BRR bank: header+table+BRR region, 73 effects)");

        // wait past reset release + CDC settle counters; a command issued
        // during reset is swallowed by design (same as the real core)
        wait (!xReset && !hReset);
        repeat (32) @(posedge xClk);

        // ---- xRamReady gate: command issued before PSRAM is ready ----
        // (BIST not finished). The play must latch and start once ready rises.
        cur_idx = 0;
        load_rec(7'd0); load_ref(7'd0);
        ncap = 0; cap_en = 1;
        start_fx(7'd0);                  // A01, while xRamReady is still 0
        repeat (300) @(posedge xClk);
        xRamReady <= 1;
        begin : gate_wait
            integer t;
            t = 0;
            while (!hPlaying && t < 3000*75000) begin @(posedge xClk); t=t+1; end
            while ( hPlaying && t < 3000*75000) begin @(posedge xClk); t=t+1; end
            repeat (200) @(posedge hClk);
            cap_en = 0;
            if (t >= 3000*75000) begin
                fails = fails + 1;
                $display("FAIL gate: timed out (playing=%b)", hPlaying);
            end else if (ncap !== exp_samples) begin
                fails = fails + 1;
                $display("FAIL gate: captured %0d, expected %0d", ncap, exp_samples);
            end else begin
                $display("fx00 A01 (gated start)");
                compare_cap(0, exp_samples);
            end
        end

        // ---- all 73 effects ----
        for (i = 1; i < 73; i = i + 1) begin
            cur_idx = i[6:0];
            $display("fx%02d (%s)", i, (psram[128 + i*8 + 4] & 16'd2) ? "loop" :
                       ((psram[128 + i*8 + 4] & 16'd1) ? "cnt" : "one"));
            if (psram[128 + i*8 + 4] & 16'd2)
                play_loop_check(i[6:0], 3000);
            else
                play_oneshot_check(i[6:0], 3000);
        end

        // ---- interrupt/retrigger: loop ambience -> one-shot ----
        $display("interrupt B01 -> A09");
        play_interrupt_check(7'd48, 7'd8, 6000, 3000);

        // ---- interrupt/retrigger with envelopes: A03 -> A02 ----
        // both have segment entries, so this refills the segment store while
        // the interrupted (envelope) effect may still be reading it; the tail
        // must still be bit-exact against ref_A02.
        $display("interrupt A03 -> A02 (both enveloped)");
        play_interrupt_check(7'd2, 7'd1, 5000, 3000);

        if (fails) $display("RESULT: FAIL (%0d)", fails);
        else       $display("RESULT: PASS");
        $finish;
    end

    // global watchdog (sim time, generous: full run is ~0.5s simulated)
    initial begin
        #5_000_000_000;
        $display("GLOBAL TIMEOUT at fx=%0d ncap=%0d", cur_idx, ncap);
        $display("RESULT: FAIL (timeout)");
        $finish;
    end

endmodule
